sudo: required
dist: trusty
language: go
## home folder is /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli
services:
- docker
matrix:
  include:
    - env: TO_TEST=e2e OPENSHIFT_VERSION=v3.9
  fast_finish: true

before_install:
- pwd
- bash --version
- sudo apt-get install --only-upgrade bash
- bash --version
- test/prepare.sh
install:
before_script:
script:
- if [ "$TO_TEST" = "e2e" ]; then make test-e2e ; fi
notifications:
 email:
   on_success: never
   on_failure: never
